apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: dotnet-todos
  description: Dot Net Todos Application
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: dev-team-1
  domain: acme-internal-apps

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sql-server
  description: SQL Server Database
spec:
  type: database
  owner: platform-team
  system: dotnet-todos
