site_name: 'TAP Demo Catalog'

nav:
  - Summary: workshop-summary.md
  - Overview: workshop-overview.md
  - 'Learning Center': exercises/01-Learning-Center.md
  - 'App Accelerator': exercises/02-App-Accelerator.md
  - 'IDE Tools': exercises/03-IDE-Tools.md
  - 'Iterative Development': exercises/04-Iterative-Development.md
  - 'App Live View': exercises/05-App-Live-View.md
  - 'Submitting Build': exercises/06-Submitting-Build.md
  - 'Work Load': exercises/07-Workload.md
  - 'Supply Chain': exercises/08-Supply-Chain.md
  - Deliverable: exercises/09-Deliverable.md

plugins:
  - techdocs-core
