apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-dev
  description: Acme Dev
spec:
  type: team
  profile:
    displayName: Acme Dev
    email: acmedev@acme.com
  children: [dev-team-1,dev-team-2,platform-team]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev-team-1
  description: Dev Team 1
spec:
  type: team
  profile:
    displayName: Dev Team 1
    email: dev-team-1@acme.com
  parent: acme-dev
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: cody
spec:
  profile:
    displayName: Cody
    email: cody@acme.com
  memberOf: [dev-team-1]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: naomi
spec:
  profile:
    displayName: Naomi
    email: naomi@acme.com
  memberOf: [dev-team-1]
---  
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev-team-2
  description: Dev Team 2
spec:
  type: team
  profile:
    displayName: Dev Team 2
    email: dev-team-2@acme.com
  parent: acme-dev
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: shmody
spec:
  profile:
    displayName: Shmody
    email: shmody@acme.com
  memberOf: [dev-team-2]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: shmaomi
spec:
  profile:
    displayName: Shmaomi
    email: shmaomi@acme.com
  memberOf: [dev-team-2]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform Team
spec:
  type: team
  profile:
    displayName: Platform Team
    email: platform-team@acme.com
  parent: acme-dev
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alana
spec:
  profile:
    displayName: Alana
    email: alana@acme.com
  memberOf: [platform-team]