apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: canary
  description: Hello world style services that platform team can use to ensure operations of the platform.
spec:
  owner: platform-team
  domain: platform-domain
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello
  description: Simple spring-boot java app demonstrating hello world capability
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=hello
    backstage.io/source-location: url:https://dev.azure.com/doddatvmware/tap-lab-canary-app/_git/hello
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: canary
  providesApis:
    - canary-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: appsso-starter-java
  description: Simple spring-boot java app demonstrating TAP app sso capability
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=appsso-starter-java
    backstage.io/source-location: url:https://dev.azure.com/doddatvmware/tap-lab-canary-app/_git/appsso-starter-java
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: canary
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: canary-api
  description: The demo API for Tanzu Application Platform GUI
  links:
  - url: https://api.agify.io 
    title: API Definition 
    icon: docs
spec:
  type: openapi
  lifecycle: production
  owner: platform-team
  system: canary # Or specify system name of your choice 
  definition: |
    openapi: 3.0.1 
    info:
      title: defaultTitle 
      description: defaultDescription 
      version: '0.1'
    servers:
      - url: https://api.agify.io
    paths: 
      /:
        get:
          description: Auto generated using Swagger Inspector 
          parameters:
          - name: name 
            in: query 
            schema:
              type: string 
            example: type_any_name
          responses: 
            '200':
              description: Auto generated using Swagger Inspector 
              content:
                application/json; charset=utf-8: 
                  schema:
                    type: string 
                  examples: {}