apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: canary
  description: Hello world style services that platform team can use to ensure operations of the platform.
spec:
  owner: platform-team
  domain: platform-domain
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello
  description: Simple spring-boot java app demonstrating hello world capability
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=hello
    backstage.io/source-location: url:https://dev.azure.com/doddatvmware/tap-lab-canary-app/_git/hello
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: canary
