apiVersion: backstage.io/v1alpha1
kind: System
metadata:
 name: dot-net-todos
 description: Dot Net Todos Application
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: devteam1
  domain: acme-internal-apps

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dot-net-todos
  description: Todos .NET
  tags:
    - microservice
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=dot-net-todos'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  providesApis:
   - dot-net-todos-api
  lifecycle: alpha
  owner: devteam1
  system: dot-net-todos

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
 name: sql-server
  description: SQL Server Database
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  type: database
  owner: platform-team
  system: dot-net-todos
---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dot-net-todos-api
  description: The API for Dot Net Todos Application
  links:
    - url: https://api.agify.io
      title: API Definition
      icon: docs
spec:
  type: openapi
  lifecycle: experimental
  owner: devteam1
  system: dot-net-todos
  definition: |
    openapi: 3.0.1
    info:
      title: Demo API
      description: defaultDescription
      version: '0.1'
    servers:
      - url: https://api.agify.io
    paths:
      /:
        get:
          description: Auto generated using Swagger Inspector
          parameters:
            - name: name
              in: query
              schema:
                type: string
              example: type_any_name
          responses:
            '200':
              description: Auto generated using Swagger Inspector
              content:
                application/json; charset=utf-8:
                  schema:
                    type: string
                  examples: {}