apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: pet-clinic
  description: Pet Clinic Application
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: devteam1
  domain: acme-internal-apps

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pet-clinic
  description: Pet Clinic Spring Boot
  tags:
    - microservice
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=pet-clinic'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  providesApis:
    - pet-clinic-api
  lifecycle: alpha
  owner: devteam1
  system: pet-clinic

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
 name: mysql
  description: Tanzu SQL MySQL Database
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  type: database
  owner: platform-team
  system: pet-clinic
---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pet-clinic-api
  description: The API for Pet Clinic Application
  links:
    - url: https://api.agify.io
      title: API Definition
      icon: docs
spec:
  type: openapi
  lifecycle: experimental
  owner: devteam1
  system: pet-clinic
  definition: |
    openapi: 3.0.1
    info:
      title: Demo API
      description: defaultDescription
      version: '0.1'
    servers:
      - url: https://api.agify.io
    paths:
      /:
        get:
          description: Auto generated using Swagger Inspector
          parameters:
            - name: name
              in: query
              schema:
                type: string
              example: type_any_name
          responses:
            '200':
              description: Auto generated using Swagger Inspector
              content:
                application/json; charset=utf-8:
                  schema:
                    type: string
                  examples: {}